const products = [
    {item: 'Tolit Paper',
     brand: 'Charmin',
     units: '4',
     quanitity: 10},
    {item: 'Paper Towel',
     brand: 'bounty',
     units: '3',
     quanitity: 8},
     {item: 'Tissue Paper',
     brand: 'Kleenex',
     units: '3',
     quanitity: 6},
     {item: '24 Pack Water Bottles',
     brand: 'AquaFresh',
     units: '15',
     quanitity: 6},
     {item: 'Monster Energy',
     brand: 'Monster',
     units: '12',
     quanitity: 30},
     {item: 'Playstion 5',
     brand: 'Sony',
     units: '3',
     quanitity: 4},
     {item: 'Xbox Series X',
     brand: 'Microsoft',
     units: '3',
     quanitity: 4},
]